In [140]:
import torch
import numpy as np
import torch.nn.functional as F

In [2]:
data = [[1,2],[3,4]]
x = torch.tensor(data)

In [3]:
x

tensor([[1, 2],
        [3, 4]])

In [4]:
np_x = np.array(data)
x_np = torch.from_numpy(np_x)

In [6]:
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
x_ones = torch.ones_like(x)

In [12]:
x_rand = torch.rand_like(x, dtype=torch.float)

In [13]:
x_rand

tensor([[0.4828, 0.8917],
        [0.3115, 0.2069]])

In [15]:
tensor = torch.rand_like(x, dtype=torch.float)

In [19]:
tensor.shape, tensor.dtype, tensor.device

(torch.Size([2, 2]), torch.float32, device(type='cpu'))

In [20]:
torch.cuda.is_available()

False

In [22]:
tensor = torch.ones(3,4)

In [23]:
tensor[1,:] = 0

In [24]:
tensor

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.]])

In [27]:
t1 = torch.cat([tensor, tensor], dim=0)

In [30]:
t1

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.]])

In [35]:
tensor.mul(tensor)

tensor([[1., 4., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.]])

In [39]:
tensor @ tensor.T

tensor([[7., 0., 5.],
        [0., 0., 0.],
        [5., 0., 4.]])

In [40]:
tensor.add_(5)

tensor([[6., 7., 6., 6.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.]])

In [41]:
tensor

tensor([[6., 7., 6., 6.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.]])

In [42]:
tensor.numpy()

array([[6., 7., 6., 6.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]], dtype=float32)

In [85]:
a = torch.rand(size=(4,3,4,4,1))
b = torch.rand(size=(4,3,4,1,1))

c = torch.matmul(a,b)
print(c.shape)

torch.Size([4, 3, 4, 4, 1])


In [86]:

y=torch.empty((2,3))

In [87]:
y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [89]:
window = torch.rand(size=(4,1))


In [90]:
m = a * window

In [98]:
b = torch.rand(2,3)


In [105]:
b

tensor([[0.6720, 0.6456, 0.2954],
        [0.4091, 0.7693, 0.4401]])

In [116]:
b.view(-1,1).sum(dim=1)

tensor([0.6720, 0.6456, 0.2954, 0.4091, 0.7693, 0.4401])

In [135]:
t = torch.rand(2,3,3)

In [136]:
t

tensor([[[0.5078, 0.1704, 0.5996],
         [0.9994, 0.1337, 0.7752],
         [0.2793, 0.1553, 0.7666]],

        [[0.6955, 0.3223, 0.5040],
         [0.7366, 0.9657, 0.6298],
         [0.0947, 0.9952, 0.9199]]])

In [137]:
t[0,:,2]=5

In [139]:
t.shape

torch.Size([2, 3, 3])

In [145]:
s = F.pad(t, pad=(0,5 - t.shape[2],0,5 - t.shape[1],0,0), mode='constant', value=6)

In [146]:
s.shape

torch.Size([2, 5, 5])

In [147]:
s

tensor([[[0.5078, 0.1704, 5.0000, 6.0000, 6.0000],
         [0.9994, 0.1337, 5.0000, 6.0000, 6.0000],
         [0.2793, 0.1553, 5.0000, 6.0000, 6.0000],
         [6.0000, 6.0000, 6.0000, 6.0000, 6.0000],
         [6.0000, 6.0000, 6.0000, 6.0000, 6.0000]],

        [[0.6955, 0.3223, 0.5040, 6.0000, 6.0000],
         [0.7366, 0.9657, 0.6298, 6.0000, 6.0000],
         [0.0947, 0.9952, 0.9199, 6.0000, 6.0000],
         [6.0000, 6.0000, 6.0000, 6.0000, 6.0000],
         [6.0000, 6.0000, 6.0000, 6.0000, 6.0000]]])

In [134]:
t.view(-1,9).sum(dim=0, keepdim=True).shape

torch.Size([1, 9])

In [152]:
s.max()

tensor(6.)

In [126]:
window * weight

tensor([[[[3.7641e-01, 5.9167e-01, 4.1914e-01],
          [5.8887e-01, 4.7407e-02, 7.8124e-02],
          [3.0555e-04, 1.3757e-01, 7.4541e-01]],

         [[2.0937e-01, 1.9380e-01, 3.0232e-01],
          [1.7815e-01, 5.4251e-02, 2.1125e-02],
          [2.1460e-01, 5.3168e-01, 2.5354e-01]],

         [[4.1129e-01, 2.3877e-01, 2.8297e-01],
          [1.4465e-01, 4.4300e-01, 7.9109e-01],
          [2.6422e-01, 1.6496e-01, 1.5933e-01]]],


        [[[4.7723e-01, 3.9363e-01, 4.3828e-01],
          [8.4241e-01, 5.5064e-01, 4.5241e-01],
          [5.2643e-03, 2.7739e-01, 4.0310e-01]],

         [[9.9674e-03, 3.9911e-01, 3.1022e-01],
          [2.7762e-01, 4.0379e-01, 8.0970e-01],
          [4.5839e-01, 5.9396e-02, 6.3095e-01]],

         [[6.0584e-02, 6.7412e-03, 4.8064e-01],
          [4.6350e-01, 2.9483e-01, 3.1592e-01],
          [2.8794e-01, 1.4728e-01, 3.2681e-01]]],


        [[[1.3222e-01, 2.5855e-01, 3.1835e-01],
          [9.9602e-02, 1.6554e-01, 1.8376e-01],
          [5.7718e-03, 1